//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.EmployeeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.AddEmployeeService")]
    public interface AddEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/AddEmployeeService/CreateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/AddEmployeeService/CreateEmployeeFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        void CreateEmployee(int id, string name, string remark, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployeeService/AddRemark", ReplyAction="http://tempuri.org/AddEmployeeService/AddRemarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/AddEmployeeService/AddRemarkFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        void AddRemark(string remark, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployeeService/ClearEmployeeList", ReplyAction="http://tempuri.org/AddEmployeeService/ClearEmployeeListResponse")]
        void ClearEmployeeList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddEmployeeServiceChannel : Client.EmployeeService.AddEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddEmployeeServiceClient : System.ServiceModel.ClientBase<Client.EmployeeService.AddEmployeeService>, Client.EmployeeService.AddEmployeeService {
        
        public AddEmployeeServiceClient() {
        }
        
        public AddEmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddEmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddEmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddEmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateEmployee(int id, string name, string remark, System.DateTime date) {
            base.Channel.CreateEmployee(id, name, remark, date);
        }
        
        public void AddRemark(string remark, int id) {
            base.Channel.AddRemark(remark, id);
        }
        
        public void ClearEmployeeList() {
            base.Channel.ClearEmployeeList();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.RetriveEmployeeService")]
    public interface RetriveEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveEmployeeService/GetAllEmployeeDetails", ReplyAction="http://tempuri.org/RetriveEmployeeService/GetAllEmployeeDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/RetriveEmployeeService/GetAllEmployeeDetailsFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        System.Collections.Generic.List<EmployeeManagementService.EmployeeDetails> GetAllEmployeeDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveEmployeeService/SearchById", ReplyAction="http://tempuri.org/RetriveEmployeeService/SearchByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/RetriveEmployeeService/SearchByIdFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        EmployeeManagementService.EmployeeDetails SearchById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveEmployeeService/SearchByName", ReplyAction="http://tempuri.org/RetriveEmployeeService/SearchByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/RetriveEmployeeService/SearchByNameFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        EmployeeManagementService.EmployeeDetails SearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveEmployeeService/SearchByRemark", ReplyAction="http://tempuri.org/RetriveEmployeeService/SearchByRemarkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EmployeeManagementService.FaultDetails), Action="http://tempuri.org/RetriveEmployeeService/SearchByRemarkFaultDetailsFault", Name="FaultDetails", Namespace="http://schemas.datacontract.org/2004/07/EmployeeManagementService")]
        EmployeeManagementService.EmployeeDetails SearchByRemark(string remark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetriveEmployeeServiceChannel : Client.EmployeeService.RetriveEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetriveEmployeeServiceClient : System.ServiceModel.ClientBase<Client.EmployeeService.RetriveEmployeeService>, Client.EmployeeService.RetriveEmployeeService {
        
        public RetriveEmployeeServiceClient() {
        }
        
        public RetriveEmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetriveEmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetriveEmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetriveEmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EmployeeManagementService.EmployeeDetails> GetAllEmployeeDetails() {
            return base.Channel.GetAllEmployeeDetails();
        }
        
        public EmployeeManagementService.EmployeeDetails SearchById(int id) {
            return base.Channel.SearchById(id);
        }
        
        public EmployeeManagementService.EmployeeDetails SearchByName(string name) {
            return base.Channel.SearchByName(name);
        }
        
        public EmployeeManagementService.EmployeeDetails SearchByRemark(string remark) {
            return base.Channel.SearchByRemark(remark);
        }
    }
}
